[project]
authors = ["Modular <hello@modular.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-gpu-puzzles"
platforms = ["linux-64"]
version = "0.0.0"

[tasks]
format = "mojo format problems solutions"

tests = { cmd = "bash solutions/run.sh" }

build-book = "cd book && mdbook build"
book = { cmd = "cd book && mdbook serve --open", depends-on = ["build-book"] }
clean = { cmd = "cd book && mdbook clean" }

p01 = "mojo problems/p01/p01.mojo"
viz01 = "cd book/src/puzzle_01 && python puzzle_01_viz.py"

p02 = "mojo problems/p02/p02.mojo"
viz02 = "cd book/src/puzzle_02 && python puzzle_02_viz.py"

p03 = "mojo problems/p03/p03.mojo"

p04 = "mojo problems/p04/p04.mojo"
viz04 = "cd book/src/puzzle_04 && python puzzle_04_viz.py"
p04_layout_tensor = "mojo problems/p04/p04_layout_tensor.mojo"

p05 = "mojo problems/p05/p05.mojo"
p05_layout_tensor = "mojo problems/p05/p05_layout_tensor.mojo"

p06 = "mojo problems/p06/p06.mojo"

p07 = "mojo problems/p07/p07.mojo"
p07_layout_tensor = "mojo problems/p07/p07_layout_tensor.mojo"

p08 = "mojo problems/p08/p08.mojo"

p09 = "mojo problems/p09/p09.mojo"

p10 = "mojo problems/p10/p10.mojo"

p11 = "mojo problems/p11/p11.mojo"

p12 = "mojo problems/p12/p12.mojo"

p13 = "mojo problems/p13/p13.mojo"

p14 = "mojo problems/p14/p14.mojo"

[dependencies]
max = "*"
bash = ">=5.2.21,<6"
python = "==3.12"
manim = ">=0.18.1,<0.19"
mdbook = ">=0.4.48,<0.5"
