name: 💡 Feature Request
description: Suggest improvements for Mojo GPU Puzzles
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve Mojo GPU Puzzles!
        This can be used for suggesting new puzzles, improving explanations, or enhancing existing content.

  - type: input
    id: puzzle
    attributes:
      label: Related Puzzle
      description: Which puzzle does this suggestion relate to? (Leave empty if it's a general suggestion)
      placeholder: "e.g., Puzzle 1: Map"
    validations:
      required: false

  - type: dropdown
    id: type
    attributes:
      label: Type of Suggestion
      description: What kind of improvement are you suggesting?
      options:
        - Puzzle Explanation
        - Code Comments
        - New Puzzle Idea
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion Details
      description: Describe your suggestion or improvement
      placeholder: |
        What would you like to see improved or added?
        If it's an explanation improvement, what was unclear?
        If it's a new puzzle idea, what concepts would it teach?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help us understand your suggestion better
    validations:
      required: false
