name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'

permissions:
  id-token: write
  contents: write

jobs:
  test:
    runs-on: github-gpu
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.modular
            ~/.cache/modular
          key: ${{ runner.os }}-modular-${{ hashFiles('**/pixi.toml') }}

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.53.0
          cache: false
          post-cleanup: false

      - name: Check formatting
        shell: bash
        run: |
          pixi run format-check

      - name: Tests
        shell: bash
        run: |
          pixi run tests

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.modular
            ~/.cache/modular
          key: ${{ runner.os }}-modular-${{ hashFiles('**/pixi.toml') }}

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.53.0
          cache: false
          post-cleanup: false

      - name: Build
        shell: bash
        run: |
          cd book
          pixi run build-book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/html
          cname: puzzles.modular.com
          allow_empty_commit: true
