name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Magic CLI
        run: |
          curl -ssL https://magic.modular.com/ | bash
          . $HOME/.bashrc
          echo "$HOME/.modular/bin" >> $GITHUB_PATH
          export PATH="$HOME/.modular/bin:$PATH"

      - name: Build
        shell: bash
        run: |
          . $HOME/.bashrc
          cd book
          magic run build-book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/html
          allow_empty_commit: true
