name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Add Rust caching
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/mojoproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Add Modular caching
      - uses: actions/cache@v3
        with:
          path: |
            ~/.modular
            ~/.cache/modular
          key: ${{ runner.os }}-modular-${{ hashFiles('**/mojoproject.toml') }}

      - name: Install Magic CLI
        run: |
          curl -ssL https://magic.modular.com/ | bash
          . $HOME/.bashrc
          echo "$HOME/.modular/bin" >> $GITHUB_PATH
          export PATH="$HOME/.modular/bin:$PATH"

      - name: Build
        shell: bash
        run: |
          . $HOME/.bashrc
          cd book
          magic run build-book

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Trigger Vercel Redeploy
        run: vercel redeploy ${{ secrets.VERCEL_DEPLOYMENT_URL }} --target stable --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/html
          cname: puzzles.modular.com
          allow_empty_commit: true
